= Home Assistant add-ons repository

image::https://img.shields.io/github/license/fboulay/ha-addons-repository.svg[licence]

== About

Here, you will find all my add-ons for Home Assistant

== Installation

Adding this add-ons repository to your Home Assistant instance is
pretty easy. Follow https://home-assistant.io/hassio/installing_third_party_addons[the official instructions] on the
website of Home Assistant, and use the following URL: 

```
https://github.com/fboulay/ha-addons-repository
```

== Available add-ons

=== link:ha-protonmail-bridge/DOCS.md[ProtonMail Bridge]

* Install the ProtonMail bridge to send emails using your ProtonMail account


==== About ProtonMail bridge

ProtonMail Bridge is an application available to all paid users that enables the integration of your ProtonMail account with any SMTP clients (in theory). 
Bridge runs in the background by seamlessly encrypting messages as they leave Home Assistant.

This addon allow to send notification emails using a ProtonMail account. 

== License

MIT License

Copyright (c) 2021 Florian Boulay

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
