= Home Assistant addon: ProtonMail Bridge

Install ProtonMail Bridge in Home Assistant, to enable notifications using a ProtonMail account.

IMPORTANT: This addon is still a work in progress, and is not yet recommended for installation

== About

ProtonMail Bridge is an application available to all paid users that enables the integration of your ProtonMail account with any SMTP clients (in theory). 
Bridge runs in the background by seamlessly encrypting messages as they leave Home Assistant.

This addon allow to send notification emails using a ProtonMail account. 

link:ha-protonmail-bridge/DOCS.md[Read the full documentation]

== Test the addon

.Build the image in the ha-protonmail-bridge directory
[source]
----
docker build --build-arg BUILD_FROM="homeassistant/amd64-base:latest" -t local/my-test-addon .
----

.Run built image
[source]
----
docker run --rm -v /tmp/my_test_data:/data -p 25:2525 local/my-test-addon
----

Inside the directory `my_test_data`, create a file called `options.json` with the correct configuration for the addon.

.Start a shell in the image to debug
[source]
----
docker run --rm -v /tmp/my_test_data:/data -p 25:2525  -ti --entrypoint bash local/my-test-addon
----

== License

MIT License

Copyright (c) 2021 Florian Boulay

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
